services:
  database:
    image: bitnami/postgresql:latest
    container_name: postgres
    restart: unless-stopped
    platform: linux/386
    ports:
      - 5432:$POSTGRES_PORT
    environment:
      # passing the $ will get the variable from .env
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - widget
      - database

  application:
    build: .
    depends_on:
      - database
    restart: unless-stopped
    container_name: upload-widget-server
    ports:
      - 3000:$PORT
    environment:
      # passing the $ will get the variable from .env
      - DATABASE_URL=$DATABASE_URL
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUDFLARE_BUCKET=$CLOUDFLARE_BUCKET
      - CLOUDFLARE_PUBLIC_URL=$CLOUDFLARE_PUBLIC_URL
    networks:
      - widget

volumes:
  database:
networks:
  widget:
    driver: bridge
  database:
    driver: bridge
